"""AXIOM :: bulk outbound messaging — the second workload, where money is the WRONG axis.

WHY THIS ONE
------------
Four candidates were on the table: destructive data operations, infrastructure
provisioning, access revocation, and bulk outbound messaging. Messaging wins on the only
criterion that matters for the argument, which is how visceral and how REAL the
double-execution failure is:

  * deleting twice is idempotent by nature — the second DELETE removes nothing, so the
    failure has to be manufactured (delete the WRONG thing), which is a targeting bug,
    not a crash-recovery bug;
  * provisioning twice leaks resources, but the harm is denominated in dollars again,
    which quietly re-imports the axis this exercise exists to escape;
  * revoking access twice is idempotent, and granting twice is idempotent;
  * sending twice puts a second copy of the same message in front of every recipient,
    and there is no undo. Not a duplicated row: forty thousand people, a burnt sending
    domain, and in several jurisdictions a compliance incident.

And it is the workload agents actually do today. An LLM agent that drafts and sends
outbound campaigns is the single most common autonomous-action product shipping right
now, which makes "what happens when it crashes mid-send" a question someone is living
with this week.

WHY DOLLARS ARE NOT MERELY THE WRONG AXIS BUT A DANGEROUS ONE
-------------------------------------------------------------
A 40,000-recipient send costs about forty cents of SES. Under a money-shaped authority
model — "the agent may act unattended up to $200" — that campaign sails through with
three orders of magnitude of headroom, while a $300 refund to one customer stops and
waits for a human. The dollar amount is not a conservative proxy for blast radius here;
it is an actively misleading one, and a policy engine that only speaks money will
cheerfully authorize the more damaging of the two actions.

So this domain's risk axis is RECIPIENTS. The policy ceiling
(axiom_policy.max_auto_action_cents, read as units) becomes "the agent may message this
many people unattended"; the mission budget (axiom_mission.budget_cents, read as units)
becomes a hard cap on the total blast radius of an entire mission. Both work. Both are
stored in columns named for money — see the note in axiom/domains/__init__.py, which
does not pretend otherwise.

THE PROVIDER THAT OFFERS NOTHING
--------------------------------
With AXIOM_SES=1 and an explicit recipient list on the payload, this domain stops
simulating and sends real email through Amazon SES (axiom/ses.py, dispatched by
axiom/domains/relay.py). That is the sharpest version of this project's argument and the
reason the second worked example is worth building rather than checking off. Stripe has
idempotency keys, so the refund example argues that AXIOM makes the key survive the crash.
SES has NO idempotent send — call SendEmail twice and two emails arrive, each with its own
MessageId, and there is no header to hand it and no replay flag to read back. So on this
path there is no shared credit: the entire guarantee is AXIOM's, or it does not exist.

WHAT THE ENGINE DID NOT NEED TO CHANGE
--------------------------------------
Nothing. Not one line of tasks.py, memory.py, policy.py or db.py. The idempotency key is
generated by the database from (tenant_id, task_id, step_name, step_seq) — no money in
it — so a crashed broadcast recovers under exactly the same key by exactly the same
mechanism as a crashed refund, and the receipt is a durable answer to "did the send
already go out?" for the same reason it answers "did the money already move?".
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Sequence

from ..config import settings
from ..models import TaskState
from ..risk import COMMS_RECIPIENTS, Reversibility, Risk, measurer
from . import AuditReport, Effect, Intent, RiskAxis, register
from . import relay

# 'RCP' is three characters because it is stored in axiom_action_attempt.currency, which
# is STRING(3). It is not a currency. `risk_unit` is the honest name for the same fact,
# and IRREVERSIBLE is not a hedge: there is no API call that un-sends an email.
RECIPIENTS = RiskAxis(unit='recipients', code='RCP', noun='recipients',
                      risk_unit=COMMS_RECIPIENTS,
                      reversibility=Reversibility.IRREVERSIBLE)


@measurer('messages.send')
def _measure_send(request_body) -> Risk:
    """How big is this act? Derived from the REQUEST BODY, not from the agent's opinion.

    The body is already SHA-256'd into axiom_action_attempt.request_fingerprint, so the
    blast radius is reproducible from the audit trail: "the agent understated how many
    people this would reach" becomes a query rather than an argument. This is the second
    operation AXIOM knows how to size — 'refunds.create' is the first, in axiom/risk.py —
    and registering it here is the whole extension point: a workload declares what its
    act costs the world, and the policy decides whether that is allowed.
    """
    return Risk.of(COMMS_RECIPIENTS, int(request_body.get('recipient_count') or 0),
                   reversibility=Reversibility.IRREVERSIBLE,
                   description=(f'campaign {request_body.get("campaign_ref", "?")} to '
                                f'segment {request_body.get("segment", "?")}'))


# ------------------------------------------------------------------------- triage

_SYSTEM = """You triage outbound messaging campaigns for an autonomous operations agent.

You do not send anything. You propose one action; a policy engine decides whether the
agent may take it unattended, and a durable state machine decides whether it already has.

Choose exactly one action:
  send     - the campaign is safe to deliver to the stated segment
  suppress - the campaign must NOT be delivered at all (no consent on record, the
             segment is a suppression list, the offer has already expired)
  hold     - a human must review before anything leaves (regulated claims, legal or
             medical copy, pricing or contractual changes, unclear audience)

Reply with ONLY a JSON object, no prose, no code fence:
{"action":"send","recipients":4800,"campaign_kind":"promotional_blast","reason":"one sentence","confidence":0.0-1.0}

recipients must be 0 unless action is "send", and must never exceed the stated audience
size. campaign_kind is a lowercase snake_case category such as promotional_blast,
transactional_notice, winback, service_incident, consent_gap, or regulated_copy."""


_KIND_RULES: tuple[tuple[re.Pattern, str, str], ...] = (
    (re.compile(r'no consent|unsubscrib|opt[- ]?out|suppression list|purchased list', re.I),
     'consent_gap', 'suppress'),
    (re.compile(r'regulated|medical|health claim|financial advice|legal notice|'
                r'price increase|contract change', re.I), 'regulated_copy', 'hold'),
    (re.compile(r'incident|outage|status update|security', re.I),
     'service_incident', 'send'),
    (re.compile(r'win[- ]?back|lapsed|dormant', re.I), 'winback', 'send'),
    (re.compile(r'receipt|order confirmation|shipping update|transactional', re.I),
     'transactional_notice', 'send'),
    (re.compile(r'promo|sale|launch|newsletter|announcement|campaign', re.I),
     'promotional_blast', 'send'),
)


def _offline_triage(description: str, reachable: int) -> Intent:
    """Deterministic rules, so the demo and the suite are hermetic and free.

    Same contract as llm._offline_triage: the engine cannot tell the two paths apart,
    because both return a PROPOSAL and neither can authorize itself.
    """
    for pattern, kind, action in _KIND_RULES:
        if pattern.search(description):
            return _intent(action, kind, reachable,
                           f'matched {kind} on the campaign brief', 0.75)
    # Nothing matched. An unclassified blast is exactly the case that must not go out
    # unattended, so the safe default is a human — never "send anyway".
    return _intent('hold', 'unclassified', 0, 'no rule matched this campaign brief', 0.4)


def _intent(action: str, kind: str, reachable: int, reason: str,
            confidence: float) -> Intent:
    return Intent(
        action=action,
        acts=(action == 'send'),
        risk_units=reachable if action == 'send' else 0,
        kind=kind,
        reason=reason,
        confidence=confidence,
        # suppress is a RESOLVED outcome: the correct handling of a campaign that must
        # not go out is to not send it and to remember why. hold is a human's problem
        # and rests in DEAD_LETTER, visible on the operator's queue.
        terminal_state=(TaskState.SUCCEEDED if action == 'suppress'
                        else TaskState.DEAD_LETTER),
    )


def _bedrock_triage(description: str, reachable: int, campaign_ref: str) -> Intent:
    from ..llm import _bedrock            # same client, same lazy boto3 import

    prompt = (f'Campaign {campaign_ref}. Audience reachable after suppression: '
              f'{reachable} recipients.\nBrief: {description}')
    body = json.dumps({
        'anthropic_version': 'bedrock-2023-05-31',
        'max_tokens': 300, 'temperature': 0, 'system': _SYSTEM,
        'messages': [{'role': 'user', 'content': prompt}],
    })
    try:
        resp = _bedrock().invoke_model(modelId=settings.llm_model, body=body)
        text = json.loads(resp['body'].read())['content'][0]['text'].strip()
        if text.startswith('```'):
            text = text.strip('`')
            text = text[text.find('{'):]
        data = json.loads(text[text.find('{'):text.rfind('}') + 1])
        action = str(data.get('action', 'hold')).lower()
        if action not in ('send', 'suppress', 'hold'):
            action = 'hold'
        # The model may propose a SMALLER audience (it may trim) but never a larger one.
        # A model that can inflate its own blast radius is a model that can talk itself
        # past the policy ceiling, which is the thing this seam exists to prevent.
        proposed = int(data.get('recipients', 0) or 0) if action == 'send' else 0
        return _intent(action, str(data.get('campaign_kind', 'unclassified')).lower(),
                       min(proposed, reachable), str(data.get('reason', ''))[:500],
                       float(data.get('confidence', 0.7)))
    except Exception as e:
        # A model failure must never become an unattended send.
        return _intent('hold', 'unclassified', 0,
                       f'triage unavailable ({type(e).__name__}); holding for a human', 0.0)


# ------------------------------------------------------------------------- domain

class BroadcastDomain:
    name = 'broadcast'
    task_type = 'broadcast'
    step_name = 'broadcast'
    policy_id = 'broadcast_authority'
    provider_name = 'relay'
    operation = 'messages.send'
    risk = RECIPIENTS

    # ---------------------------------------------------------------- description

    def describe(self, payload: dict) -> str:
        return payload.get('description', '')

    def subject_ref(self, payload: dict) -> str:
        return payload.get('campaign_ref') or payload.get('dedupe_key', '')

    @staticmethod
    def reachable(payload: dict) -> int:
        """Audience minus the suppression list. THE number the policy judges.

        Computed from the payload rather than proposed by the model, so the quantity the
        authority check sees is a fact about the audience and not a thing the model can
        move. The model may trim it further; it may not raise it.
        """
        return max(0, int(payload.get('recipient_count', 0))
                   - int(payload.get('suppressed_count', 0)))

    # --------------------------------------------------------------------- triage

    def triage(self, payload: dict) -> Intent:
        reachable = self.reachable(payload)
        if settings.offline:
            return _offline_triage(self.describe(payload), reachable)
        return _bedrock_triage(self.describe(payload), reachable,
                               self.subject_ref(payload))

    # --------------------------------------------------------------- memory text

    def situation(self, payload: dict, intent: Intent) -> str:
        return f'{intent.kind}: {self.describe(payload)}'

    def recovery_situation(self, payload: dict) -> str:
        return (f'{payload.get("campaign_kind", "unknown")}: '
                f'{payload.get("description", "")}')

    # -------------------------------------------------------------- the request

    def request_body(self, payload: dict, intent: Intent) -> dict:
        # template_sha is in the body ON PURPOSE. The fingerprint then means "the same
        # copy to the same people", so a recovered agent that re-synthesizes the message
        # with one word changed is rejected by the relay with a 409 instead of quietly
        # sending different copy under a key that promised the original. That is crash
        # window W7 with the stakes a marketing team would actually recognize.
        body = {'campaign_ref': self.subject_ref(payload),
                'segment': payload.get('segment', 'all'),
                'recipient_count': intent.risk_units,
                'template_sha': hashlib.sha256(
                    self.describe(payload).encode()).hexdigest()[:16],
                'reason': intent.kind}
        # An explicit address list is the real-gateway shape, and it belongs IN the body
        # rather than beside it. Two consequences, both wanted: the list is covered by
        # request_fingerprint, so a recovered agent that re-synthesizes the campaign with
        # one address changed is a 409 rather than a surprise inbox; and the receipt
        # re-sends it verbatim, so recovery cannot mail a list the policy never saw.
        # Absent for the count-only campaigns, which keeps their fingerprints byte-for-byte
        # what they have always been.
        if payload.get('recipients'):
            body['recipients'] = [str(a) for a in payload['recipients']]
        return body

    def dispatch(self, *, idempotency_key: str, request_body: dict, risk_units: int,
                 chaos_pre: float | None = None,
                 chaos_post: float | None = None) -> Effect:
        r = relay.send(
            idempotency_key=idempotency_key,
            campaign_ref=request_body['campaign_ref'],
            segment=request_body.get('segment', 'all'),
            recipient_count=risk_units,
            request_body=request_body,
            # None on every existing path. With AXIOM_SES=1 and a list present these
            # addresses receive real email through Amazon SES, and the relay's own store
            # is the only thing preventing a second copy — SES has no idempotency key to
            # be handed. See axiom/ses.py.
            recipients=request_body.get('recipients'),
            chaos_pre=chaos_pre, chaos_post=chaos_post)
        return Effect(ref=r['id'], status=r['http_status'], body=r,
                      replayed=r['replayed'])

    def settled_memory(self, *, situation: str, idempotency_key: str, risk_units: int,
                       effect: Effect, first_try: bool) -> str:
        verb = 'REPLAYED' if effect.replayed else 'DELIVERED'
        text = (
            f'{situation} | recovered={not first_try} | relay {verb} {effect.ref} to '
            f'{risk_units} recipients under key {idempotency_key}'
            if not first_try else
            f'{situation} | campaign {effect.ref} delivered to {risk_units} recipients '
            f'on the first attempt')
        # On the real path the memory sentence carries the EVIDENCE rather than a claim:
        # SES MessageIds, and how many messages this particular call caused SES to accept
        # (zero, on a replay). Appended only when the send actually went through SES, so
        # every existing memory row is byte-for-byte what it has always been.
        if effect.body.get('channel') == 'ses':
            ids = ', '.join(effect.body.get('message_ids') or []) or 'none recorded'
            text += (f' | SES accepted {effect.body.get("ses_accepted", 0)} message(s) on '
                     f'this call; MessageIds {ids}')
        return text

    # ---------------------------------------------------------------- the audit

    def audit(self, subject_refs: Sequence[str] | None = None) -> AuditReport:
        s = relay.stats(subject_refs)
        return AuditReport(
            effects=int(s['sends']),
            risk_units=int(s['deliveries']),
            replays=int(s['replays']),
            verdicts=s['verdicts'],
            duplicates=relay.duplicate_recipients(subject_refs),
            duplicate_label='recipients who received the same campaign twice',
        )


DOMAIN = register(BroadcastDomain())
